version: 2.6.{build}
branches:
  only:
  - master
max_jobs: 1
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}.0-pre'
environment:
  NuGetApiKey:
    secure: bsq7k6KBk+iI9LutJ6wQKuJr3P5qf0sEfgD05BGK31V6DXQYfLWrEk9Dpx2zw+7a
install:
- ps: >-
    $zipPath = "$($env:APPVEYOR_BUILD_FOLDER)\xpkg.zip"
    
    (New-Object Net.WebClient).DownloadFile('https://components.xamarin.com/submit/xpkg', $zipPath)
    
    7z x $zipPath | Out-Null
    
    Set-Content -path "$env:USERPROFILE\.xamarin-credentials" -value "xamarin.com,$env:XAMARIN_COOKIE"
xamarin:
  email: mathieu.mack@econocom.com
  password:
    secure: yyVQJ+kfRDCu6D5ABvSA1g==
  android: true
  ios: true
before_build:
- cmd: >-
    nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
    
    nuget restore MvvX.Plugins.CouchBaseLite.sln -verbosity detailed
    
    xamarin-component.exe restore MvvX.Plugins.CouchBaseLite.sln
build:
  verbosity: minimal
on_success:
- ps: '& "packageGenerator.ps1"'